### ISSUE TITLE
the tool dont work with ip, just TLD domain

### ISSUE THREAD

**Issue by redpostmanRD** [flashnuke/WebRecon#2] opened 2022-10-06 04:13 UTC
![image](https://user-images.githubusercontent.com/56092365/194212224-a127a8a9-2df0-4d84-8c5e-559bfd43f814.png)

![image](https://user-images.githubusercontent.com/56092365/194212383-3130e8ee-4885-43f2-91d0-5467449f183d.png)

![image](https://user-images.githubusercontent.com/56092365/194212433-72939076-b9ec-43c7-a64b-267b22451524.png)

**Comment by flashnuke** [comment] 2022-10-06 08:32
Thanks for raising this!

In order to reproduce this, I used the same HTB machine you did for testing (`OpenSource`), and ran a content scan with `upcloud` word in the list:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/59119926/194262547-3f17321d-3dbd-4714-960d-d904525fbeca.png">

seems to be working now, merging this PR with the fix: https://github.com/flashnuke/WebRecon/pull/3

Please pull latest and let me know if this can be closed

**Comment by flashnuke** [comment] 2022-10-25 05:24
closing

**Closed as completed by flashnuke** 2022-10-25 05:24 UTC
